### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [tejas-ardeshna/TJProfileImage#1]
Hey @tejas-ardeshna, your lib is awesome but your README lacks an Usage Example section
I created this [iOS README template](https://github.com/awesome-labs/iOS-readme-template) to help you out 😉 

Please fix these issues before we can approve [the AwesomeiOS PR](https://github.com/vsouza/awesome-ios/pull/1959)

**Comment by tejas-ardeshna** [comment]
@lfarah i have made changes accordingly. Thanks.

**Comment by lfarah** [comment]
Hey @tejas-ardeshna, you're still missing an implementation example, like this:
https://github.com/awesome-labs/iOS-readme-template#usage-example
