### ISSUE TITLE
No licence specified.

### ISSUE THREAD

**Issue by Codeglee** [tejas-ardeshna/TJProfileImage#2]
We'd love to use this, but can't without knowing the terms of the licence.

**Comment by tejas-ardeshna** [comment]
@Codeglee No copy right buddy, You can use it.

**Comment by Codeglee** [comment]
Unfortunately [we can't](https://blog.codinghorror.com/pick-a-license-any-license/) without one.
You could add an MIT licence like this https://en.wikipedia.org/wiki/MIT_License

**Comment by tejas-ardeshna** [comment]
@Codeglee  Done. Happy coding.

**Comment by Codeglee** [comment]
Awesome, thanks!
